# Generated by Django 4.2.28 on 2026-02-04 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.TextField()),
                ('mode', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=10)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('ranges', models.JSONField(blank=True, null=True)),
                ('strict_1080', models.BooleanField(default=False)),
                ('min_height_fallback', models.IntegerField(default=720)),
                ('subtitle_langs', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
