# Generated by Django 4.2.28 on 2026-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='burn_subtitles',
            field=models.BooleanField(default=False),
        ),
    ]
