# Generated by Django 4.2.28 on 2026-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_job_burn_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_clips',
            field=models.IntegerField(default=0),
        ),
    ]
