# Generated by Django 4.2.28 on 2026-02-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_job_max_clips'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='download_sections',
            field=models.BooleanField(default=False),
        ),
    ]
