# Generated by Django 4.2.28 on 2026-02-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_job_download_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_captions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_caption_lang',
            field=models.CharField(default='id', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='whisper_model',
            field=models.CharField(default='tiny', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=10),
        ),
    ]
