# Generated by Django 4.2.28 on 2026-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_job_auto_captions_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='youtube_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('local', 'Local')], default='youtube', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='local_video_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='local_video_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
